


name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*' # Запускается при создании тегов вида v1.0.0
  pull_request:
    branches:
      - main
  workflow_dispatch: # Добавлен триггер для ручного запуска

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            ~/.docker/cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
      
      - name: Build and test
        run: |
          docker build -t my-app .
          docker run --rm my-app test

  publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Build Docker image
        run: |
          docker build -t my-app:${{ github.ref_name }} .
      
      - name: Push Docker image
        run: |
          docker tag my-app:${{ github.ref_name }} ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.ref_name }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.ref_name }}
